### ISSUE TITLE
how to hide minimap 

### ISSUE THREAD

**Issue by oeyoews** [replit/codemirror-minimap#37]
Can I add a configuration to display the minimap on mouse hover, just like vscode's minimap?

**Comment by bradymadden97** [comment]
I can't find the setting in VSCode to show/hide the entire minimap on hover. Are you talking about showing/hiding the scroller on hover, like this:

https://github.com/replit/codemirror-minimap/assets/16962017/b81c9e9e-734e-4295-8c72-3575a760b2a0

If so, that's possible today in `@replit/codemirror-minimap` with the option `showOverlay: 'mouse-over'`

If not, could you point me to the vscode setting to show/hide the entire minimap on hover?

**Comment by oeyoews** [comment]
<img width="716" alt="image" src="https://github.com/replit/codemirror-minimap/assets/72405338/27550609-bee1-4f27-a55d-9af5746a7714">

**Comment by oeyoews** [comment]
I've seen it occasionally recently too

**Comment by bradymadden97** [comment]
Thanks for the pointer! 

https://github.com/replit/codemirror-minimap/pull/38 will address this with a new configuration option
